### PR TITLE
Give all version info

### LINKED ISSUE #125: Give all version info and more to the LogLady
* **What are you trying to do?**
@fitzoh reported issue #124 and even though we have more logging and thats good .... its not super useful to only know that the version was 0.1.17. We could log more details about the actual binary version (all the version info we have). Other details such as os version, cpu architecture,   even what binary cpu architecture nancy is currently being used (32 bit/64 bit version). 

* **What feature or behavior is this required for?**
Better debugging capabilities

* **How could we solve this issue? (Not knowing is okay!)**
LogLady will lead your way  

* **Anything else?**

cc @bhamail / @DarthHater

### PR DESCRIPTION
**Pull request by protoworlock69**
Populated architecture and operating system based on run time package 

It relates to the following issue #s:
* Fixes #125

cc @bhamail / @DarthHater

### CODE REVIEW

**Comment by DarthHater** [comment]
@zendern @bhamail you think we need any more bits than this? This seemed like enough to me to deduce what is going on. MAYBE OS version?

**Comment by zendern** [comment]
@protoworlock69 @DarthHater Changes look good overall. Yeah if you can get OS version sure why not.... but where those details where added doesn't help a ton now that we trunc the file every time. Flow right now would be if you ask the user to dump the logs they will have to explicitly capture them once and then run version command and capture that set. Was hoping for it all in one go. 

https://github.com/sonatype-nexus-community/nancy/blob/209a15f9d9bb83cf9a42cd9809d81b304b05a797/main.go#L80
^^ I think this is where we would also want to update.

**Comment by DarthHater** [comment]
Sounds good!

**Comment by bhamail** [comment]
While looking into this, I noticed an odd message in the beginning of the output:

```
open /Users/bhamail/.ossindex/.oss-index-config: no such file or directory
```

I'll look into why that path is being executed, maybe create an Issue and/or PR.

**Comment by DarthHater** [comment]
@bhamail check #127 , that PR should at least drop the fmt that causes that!

**Comment by protoworlock69** [comment]
@zendern feedback addressed, Jeffry and I looked at getting Operating System version and decided it was more trouble than it was worth (varies due to cross platform issues).

**Pull request merged**
