### PR TITLE
Fix parsing of CLI flags when using stdIn invocation.

### PR DESCRIPTION
**Pull request by bhamail**
Support passing in CLI flags when invoking Nancy using the standard-input pipe approach.

e.g.

```
go list -m all |  ./nancy -quiet
```

Fixes Issue #88 

cc @bhamail / @DarthHater

### CODE REVIEW

**Comment by DarthHater** [comment]
@zendern you mind taking a gander here? The config stuff was largely your ball court, I think you'll have the best eye!

**Comment by zendern** [comment]
@bhamail @DarthHater Found it and my bad!! 😢 
https://godoc.org/github.com/stretchr/testify/assert#ObjectsAreEqual

Apparently this does no assertion. Working on trying to switch it over to an method that does an assert but having issues with the logurus formatters since they are pointers.

**Comment by zendern** [comment]
Now you should see a failing test for the standard in and quiet scenario in 38f8e29. Had to fiddle all the formatters.

**Comment by bhamail** [comment]
Excellent. I'm off and running again. Thanks @zendern !

**Pull request merged**
