### PR TITLE
Avoid copying a lock by value, which is invalid.

### PR DESCRIPTION
**Pull request by flimzy**
It is not valid to copy a `sync.Mutex` value. From the [docs](https://golang.org/pkg/sync/#Mutex):

> A Mutex must not be copied after first use.

Doing so can lead to undefined results.

This PR fixes that, by passing a pointer to the value, rather than dereferencing the value before passing it.

### CODE REVIEW

**Comment by flimzy** [comment]
Incidentally, I discovered this while debugging #58, thanks to running `golangci-lint` in my editor. I notice there are several other linter failures in this repo, some of which may represent real bugs. If you'd find it valuable, I'd be happy to submit fixes for all of them. It might be worth adding `golangci-lint` to your Travis-CI script as well.

**Comment by fitzoh** [comment]
looks like `go vet` catches it as well:
```
$ go vet
# github.com/sonatype-nexus-community/nancy
./main.go:102:56: call of packages.ExtractPurlsUsingDep copies lock value: github.com/golang/dep.Project contains sync.Once contains sync.Mutex
```

**Comment by flimzy** [comment]
> looks like go vet catches it as well:

`golangci-lint` calls `go vet` (and many other linters), so that's probably what I was running, too :)

**Comment by zendern** [comment]
Well we are doing neither in CI and probably makes sense to do something there.

@flimzy what if we open an issue, get a little feedback and see about adding at least `go vet` if not `golangci-lint` to the project. 

@flimzy are you just running the default setup for `golangci-lint` or do you have other linters/checks enabled?? 

^^^I think the biggest thing with introducing that one is we just have to come to a little agreement what we do and don't want enabled. And really once we do it here it's probably going to get copied to other golang projects here like ahab.

**Comment by flimzy** [comment]
> @flimzy what if we open an issue, get a little feedback and see about adding at least go vet if not golangci-lint to the project.

Makes sense to discuss in an issue, rather than here :)

> @flimzy are you just running the default setup for golangci-lint or do you have other linters/checks enabled??

I was using the default configuration. Although in most projects, I do use a custom config to enable a few non-default linters.

**Comment by DarthHater** [comment]
@zendern @flimzy this is technically an API change (although I doubt it's going to really hurt anyone), should we bump to 0.1.0 for Nancy?

**Comment by zendern** [comment]
> @zendern @flimzy this is technically an API change (although I doubt it's going to really hurt anyone), should we bump to 0.1.0 for Nancy?

Yeah i think that is reasonable to do.

**Comment by DarthHater** [comment]
I'll try and get this merged tomorrow, I think it'll be Nancy 0.1.0 FTR! cc @zendern @flimzy

**Pull request merged**
