### PR TITLE
Add usage section to README

### PR DESCRIPTION
**Pull request by packrat386**
Add usage section to README

cc @bhamail / @DarthHater

### CODE REVIEW

**Comment by packrat386** [comment]
@fitzoh @DarthHater how does this look?

**Comment by fitzoh** [comment]
Oops, left a comment earlier but it looks like my phone ate it.

Looks good to me, just missing the flag that was added in #30.

**Comment by DarthHater** [comment]
Yeah, just needs the `-exclude-vulnerability` flag added @packrat386 !

**Comment by packrat386** [comment]
Updated.

Y'all may want to consider standardizing on `lisp-case` vs `camelCase` for flags, but that can be done some other time.

**Comment by fitzoh** [comment]
Yeah, that's a little gross when it's laid out like that

**Comment by zendern** [comment]
Im happy to open a PR changing it. The only one that is not `lisp-case` or all lowercase is `noColor`. I'd throw a vote in for `lisp-case` because from the looks of it most other golang based clis (kubectl, packer, aptly, etc) are using `lisp-case`.

**Pull request merged**
